// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Group_4_DB.Models;

namespace Group_4_DB.Data
{
    public partial class academic_settingsContext : DbContext
    {
        public academic_settingsContext()
        {
        }

        public academic_settingsContext(DbContextOptions<academic_settingsContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<Major> Majors { get; set; }
        public virtual DbSet<Majorclass> Majorclasses { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Studentclass> Studentclasses { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Class>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("classes");

                entity.Property(e => e.AttendanceType)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.ClassId)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("ClassID");

                entity.Property(e => e.ClassName)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.InstructorsId)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("InstructorsID");
            });

            modelBuilder.Entity<Instructor>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("instructors");

                entity.Property(e => e.Iemail)
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("IEmail");

                entity.Property(e => e.IfirstName)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("IFirstName");

                entity.Property(e => e.IlastName)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("ILastName");

                entity.Property(e => e.InstructorsId)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("InstructorsID");
            });

            modelBuilder.Entity<Major>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("major");

                entity.Property(e => e.EstimatedCompletion)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.MajorId)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("MajorID");

                entity.Property(e => e.MajorName)
                    .HasMaxLength(20)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Majorclass>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("majorclasses");

                entity.Property(e => e.ClassId)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("ClassID");

                entity.Property(e => e.MajorId)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("MajorID");
            });

            modelBuilder.Entity<Student>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("students");

                entity.Property(e => e.Gpa).HasColumnName("GPA");

                entity.Property(e => e.GradYear).HasColumnType("date");

                entity.Property(e => e.MajorId)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("MajorID");

                entity.Property(e => e.SfirstName)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("SFirstName");

                entity.Property(e => e.SlastName)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("SLastName");

                entity.Property(e => e.StudentId)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("StudentID");
            });

            modelBuilder.Entity<Studentclass>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("studentclasses");

                entity.Property(e => e.ClassId)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("ClassID");

                entity.Property(e => e.StudentId)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("StudentID");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}