// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Group_4_DB.Models
{
    public partial class instructors
    {
        public string InstructorsID { get; set; }
        public string IFirstName { get; set; }
        public string ILastName { get; set; }
        public string IEmail { get; set; }
        public byte IsAdviser { get; set; }
    }
}