// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Group_4_DB.Models
{
    public partial class major
    {
        public string MajorID { get; set; }
        public string MajorName { get; set; }
        public int TotalCredits { get; set; }
        public string EstimatedCompletion { get; set; }
        public byte LaptopRequired { get; set; }
    }
}