// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Group_4_DB.Models
{
    public partial class students
    {
        public string StudentID { get; set; }
        public string MajorID { get; set; }
        public string SFirstName { get; set; }
        public string SLastName { get; set; }
        public double? GPA { get; set; }
        public DateTime GradYear { get; set; }
    }
}