// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Group_4_DB.Models
{
    public partial class Student
    {
        public string StudentId { get; set; }
        public string MajorId { get; set; }
        public string SfirstName { get; set; }
        public string SlastName { get; set; }
        public double? Gpa { get; set; }
        public DateTime GradYear { get; set; }
    }
}